; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:spresense]
platform = sonyspresense
board = spresense
framework = arduino

build_src_filter =
  +<./>                                   ; 自分のsrcフォルダをビルド対象に
  +<../external/doomgeneric/doomgeneric/> ; doomgenericフォルダもビルド対象に
  
  ; doomgeneric内の、他のプラットフォーム用ファイルを除外する
  -<../external/doomgeneric/doomgeneric/doomgeneric_allegro.c>
  -<../external/doomgeneric/doomgeneric/doomgeneric_emscripten.c>
  -<../external/doomgeneric/doomgeneric/doomgeneric_linuxvt.c>  
  -<../external/doomgeneric/doomgeneric/doomgeneric_sdl.c>
  -<../external/doomgeneric/doomgeneric/doomgeneric_soso.c>
  -<../external/doomgeneric/doomgeneric/doomgeneric_sosox.c>
  -<../external/doomgeneric/doomgeneric/doomgeneric_win.c>
  -<../external/doomgeneric/doomgeneric/doomgeneric_xlib.c>
  -<../external/doomgeneric/doomgeneric/i_endoom.c>
  -<../external/doomgeneric/doomgeneric/i_allegromusic.c>
  -<../external/doomgeneric/doomgeneric/i_allegrosound.c>
  -<../external/doomgeneric/doomgeneric/i_sdlsound.c>
  -<../external/doomgeneric/doomgeneric/i_sdlmusic.c>

build_flags =
  -D __DJGPP__ ; 古いDOS開発環境用の定義。system で何もしなくなる
  -I external/doomgeneric/doomgeneric

lib_deps =
    lovyan03/LovyanGFX

upload_command = ${platformio.packages_dir}/tool-spresense/flash_writer/windows/flash_writer -s -c $UPLOAD_PORT -b $UPLOAD_SPEED -d -n -s $SOURCE
upload_speed = 1000000
